
services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: vidly_web:1
    ports:
      - 80:80
    restart: unless-stopped
  api:
    build: ./backend
    image: vidly_api:1
    ports:
      - 3001:3001
    command: ./docker-entrypoint.sh
    environment:
      DB_URL: mongodb://db/vidly
    restart: unless-stopped
  db:
    image: mongo:6.0
    ports: 
      - 27017:27017
    volumes:
      - vidly:/data/db
    restart: unless-stopped

volumes:
  vidly:
